### PR TITLE
Typo: remove erroneous dot to fix build warning

### LINKED ISSUE #544: Jekyll complains about superfluous dot in template
Building an outputted jekyll site, I get the following warning:

```
Liquid Warning: Liquid syntax error (line 19): Expected id but found open_square in "{{ site.data.datapackage.publishers.first.['web'] }}" in index.html
```

This error appears to be caused by a superfluous dot on this line:
https://github.com/theodi/octopub/blob/17db4b6f/extra/html/index.html#L23

Removing the dot fixes the warning.

### PR DESCRIPTION
**Pull request by andylolz**
This fixes one warning in the jekyll build of the static data site (#536 fixes two more).

Fixes #544.

### CODE REVIEW

**Comment by quadrophobiac** [comment]
Hey @andylolz - was this PR intended to fix the build errors showing up in Travis? 
I merged in recent changes from Master into this PR (because the no of files changed was minimal) to see if it made a difference to Travis but it did not.
I copy pasted the change suggested in this PR to my local octopub and I have no failing specs on a `bundle exec rspec` - is that what you see locally as well?

**Comment by quadrophobiac** [comment]
@Floppy it looks like most of the fails on Travis are down to `ENV['GITHUB_USER']` being inaccurate or not available to Travis - do you have any idea why/how that might have happened?

**Comment by quadrophobiac** [comment]
@Floppy it looks like most of the fails on Travis are down to `ENV['GITHUB_USER']` being inaccurate or not available to Travis - do you have any idea why/how that might have happened?
Asking in case you might have an immediate idea on resolution

**Comment by andylolz** [comment]
@quadrophobiac wrote:
> was this PR intended to fix the build errors showing up in Travis?

Sorry, no – this is about the jekyll build (of the static data site) rather than the travis build (of octopub). Apologies for lack of clarity! I’ve updated the description.

Btw did you spot #541 re. the travis errors?

**Comment by andylolz** [comment]
Blocked until #543 is merged.

**Pull request merged**
