### PR TITLE
Make resource navbar link to jekyll home

### LINKED ISSUE #526: navbar-header link should target dataset index not username.github.io
`navbar-header` link should link back to dataset/sub-site index by default, not `username.github.io`

`navbar-header` links back to root of `username.github.io`

If I look at [this dataset](https://bobharper1.github.io/uk-government-cats-training-set/data/main-list-of-cats/) (for example) the title link 'UK Government Cats - Training Set' links to https://bobharper1.github.io/ which in this case is a 404. It would be more natural for this to link back to the [dataset index]( https://bobharper1.github.io/uk-government-cats-training-set/)

In a case like [this dataset](https://stephen-gates.github.io/comma-chameleon-release-downloads/data/comma-chameleon-release-downloads/) (for example) its a bit less odd because 'Comma Chameleon Release Downloads' is a link to something that actually exists but it would still make more sense for it to link to https://stephen-gates.github.io/comma-chameleon-release-downloads/ instead of https://stephen-gates.github.io/

On [this dataset](https://democracyclub.github.io/wheredoivote-usage-june-2017/data/wheredoivote-usage-june-2017/) I've [edited](https://github.com/DemocracyClub/wheredoivote-usage-june-2017/commit/12e4144b039d31c561aa84b20543487276adfd45) the link to get the desired behaviour but I think this should be the default.

platform-independent

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #526.

### CODE REVIEW

**Comment by andylolz** [comment]
Blocked until #543 is merged.

**Comment by quadrophobiac** [comment]
Hey @andylolz, thanks for all the input on Octopub. I've added you to the Octopub team so you now have push access to this repository, hoping to continue working together on this in the future!

**Comment by andylolz** [comment]
Cool! Thanks for reviewing & merging! And thanks for the invite!

**Comment by quadrophobiac** [comment]
good to have you aboard - there's a nascent gitter room here to reach other contributors to the toolbox https://gitter.im/theodi/toolbox

**Pull request merged**
