### PR TITLE
Fix adding files

### LINKED ISSUE #552: Adding files to datasets doesn't actually add them to GitHub

### PR DESCRIPTION
**Pull request by Floppy**
This PR fixes #552

Changes proposed in this pull request:
- Push added files immediately so that the additions aren't lost when the jekyll service object is destroyed.

### CODE REVIEW

**Comment by Floppy** [comment]
I decided on doing two pushes, btw, because making the jekyll service object persist would have been a deeper code change. We can always get that in a refactor later.

**Comment by quadrophobiac** [comment]
Are those tests failing or passing locally @Floppy ?

**Comment by Floppy** [comment]
Yeah, failing here, I missed something. Will push a better fix soon.

**Comment by Floppy** [comment]
Should work now. I looked at trying to get it down to a single push, but the adds and updates are being done in different jobs, so it wasn't really viable.

**Pull request merged**
