### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by pezholio**
A short getting started guide, allowing people to get to grips with Octopub. Screencast coming soon!

### CODE REVIEW

**Comment by Floppy** [comment]
@quadrophobiac can you take a look over this?

**Comment by quadrophobiac** [comment]
@pezholio I'm showing my lack of github nous here but is there a way that you can add that branch to Octopub such that I can checkout the branch locally and check if the same tests fail locally as are crapping out on travis? I'm not even sure what the correct git nomenclature is to use for this request - is it possible?

**Comment by pezholio** [comment]
I've just restarted the build, but I suspect what's happened here is down to secret stuff not being encrypted correctly, because this is from a fork. I've not written any new tests, and none of this has any bearing on how the app functions, so it should be fine to merge :+1:

**Comment by pezholio** [comment]
That said, there is a conflict now. I'll fix that up and push it now

**Comment by pezholio** [comment]
Should be good for merge now 👍

**Comment by quadrophobiac** [comment]
Hey @pezholio thanks for getting back to me, just picking this up after being off yesterday.
There's still a failure with Travis which is inexplicable given that none of your code changes the GitData model. @Floppy have you seen Travis behave like this on this repo before? The coveralls reduction is explicable but not sure what to do about the Travis failures

**Comment by Floppy** [comment]
Oh, that's wierd. It looks like it's not set any of the ENV vars. It mentions it ran on a beta platform, perhaps it's something to do with that. I'll dig in.

**Comment by pezholio** [comment]
I'm wondering if it's something to do with the way env variables get encrypted by Travis, as this is coming from a fork

**Comment by Floppy** [comment]
oh, it's building from a fork - that'll explain it.

**Comment by Floppy** [comment]
sorry, should have read back. I remember seeing that in an email but forgot. OK, we can pull it in and merge manually with test run.

**Comment by Floppy** [comment]
This is a strong argument against using encrypted variables in tests. We shouldn't need to do it here anyway, I'll have a cleanup.

**Comment by quadrophobiac** [comment]
@Floppy when you say "merge manually with test run" is that a process that can be overridden in the merge screen?

**Comment by Floppy** [comment]
so what I did was to create a branch on this repo, pull @pezholio's changes into it, then the tests run on that one and we can merge it. That one was #418.

**Comment by Floppy** [comment]
Then when you merge that one, GitHub notices that it's the same as this one and marks this one merged as well. Clever GitHub.

**Comment by quadrophobiac** [comment]
Cool - very good to know that for future

**Comment by Floppy** [comment]
It's basically the first step of the command-line merge instructions that github shows for each PR.

**Pull request merged**
