### PR TITLE
Whitespace in file upload - WiP 

### PR DESCRIPTION
**Pull request by quadrophobiac**
RE #427

### CODE REVIEW

**Comment by quadrophobiac** [comment]
@Floppy (or anyone) I can't fix this before leaving today. This is an urgent fix - at present anyone using Octopub that uploads a file with whitespace (maybe just whitespace separators) will simply face a hanging application.
The reason I can't fix this is down to this:
I've included a js function to replace whitespace with dashes.
If you run the application locally and upload `test-data.csv` with this whitespace replacing function the file uploads fine with the following visible in the logs:
```
DatasetsController: In process_files
file is not an http uploaded file, it's a URL
DatasetsController: In check_mandatory_fields
DatasetsController: In create
CreateDataset: In perform
DatasetFile: In new_file
DatasetFile: In file_from_url_with_storage_key
Dataset file created using new file #<ActionDispatch::Http::UploadedFile:0x007fdc91479058> key: uploads/17fae1a1-c0cf-47a5-b67c-2b3b5754d1ec/test-data.csv
```

If you upload the fixture `white space.csv` - also with whitespace replacing function - you get this
```
DatasetsController: In process_files
file is not an http uploaded file, it's a URL
DatasetsController: In check_mandatory_fields
DatasetsController: In create
CreateDataset: In perform
DatasetFile: In new_file
DatasetFile: In file_from_url_with_storage_key
method=POST path=/datasets format=*/* controller=DatasetsController action=create status=500 error='Aws::S3::Errors::NoSuchKey: The specified key does not exist.' duration=372.93 view=0.00 db=0.00
Aws::S3::Errors::NoSuchKey - The specified key does not exist.:
```

This suggests to me that there is some interoperation between the various controllers of the application that is interacting with the JS in a strange way. I don't know this codebase well enough to fix this expediently - so I need help

**Comment by Floppy** [comment]
OK, I'm not around this afternoon unfortunately but I'll take a look while you're off. Thanks for the notes :)

**Comment by quadrophobiac** [comment]
Very likely that csvlint gem is causing the behaviour which this PR has attempted to fix https://github.com/theodi/csvlint.rb/issues/182

**Comment by Floppy** [comment]
Merged into #567

**Pull request closed without merging**
