### PR TITLE
Private publishing

### PR DESCRIPTION
**Pull request by Floppy**
Another WIP for now

### CODE REVIEW

**Comment by jamesjefferies** [comment]
That looks fine to me. I've delayed myself a bit this morning by looking at the production of the Jekyll pages - there's something about it sitting in ```dataset.rb``` which makes me a bit jumpy, so I started having a quick play with having that as a service. Glad I stopped though as it would have been merge fun with this PR ;) Don't know what you think, maybe another issue if we have time?

**Comment by Floppy** [comment]
Yes, good idea, make a refactor ticket. I've got more to come here, which will separate it out further in terms of when it happens, and will make that later refactor easier.

**Comment by Floppy** [comment]
I've got one test flicker on here which I'll resolve before merging.

**Comment by Floppy** [comment]
no, it's gone. I don't think it's from this PR though, it's in the user get all datasets test.

**Comment by Floppy** [comment]
Part of #204

**Pull request merged**
