### PR TITLE
Integrate csv2rest

### PR DESCRIPTION
**Pull request by Floppy**
WIP, not complete yet, but well on the way.

### CODE REVIEW

**Comment by pezholio** [comment]
🙌

**Comment by Floppy** [comment]
Mm, the test "passes" with it's dodgy things in there, but the files didn't appear when I published something up to github. I've been struggling with the ordering of file creation in the test, and TBH I have no idea if I'm doing it right. All thoughts welcome.

**Comment by Floppy** [comment]
Oh and it fails on travis. FML.

**Comment by pezholio** [comment]
Just had a quick look and it seems like the schema isn't getting picked up for some reason

**Comment by pezholio** [comment]
I think this might be because we're posting using Jquery - it's not passing through the file. Probably the best solution is to upload the schema through S3 as we do with the files.

**Comment by Floppy** [comment]
Oh, schema not getting picked up at all? Odd. How much rewiring would be needed to get the schema uploading the same way?

**Comment by pezholio** [comment]
Easy I reckon - frontend is just a case of adding a div wrapper with a class of `bg-upload`, and then downloading and parsing the file on the server side

**Comment by Floppy** [comment]
OK, sounds reasonable. Does the test look rightish to you?

**Comment by pezholio** [comment]
Just pushed a commit for the frontend

**Comment by Floppy** [comment]
You know it's Saturday? I'm only working because I was so useless yesterday...

**Comment by Floppy** [comment]
close:
```
10:01:36 worker.1 | 2016-06-25T09:01:36.828Z 14784 TID-ouo1caxtw WARN: NoMethodError: undefined method `tempfile' for #<String:0x007f8776476da0>
10:01:36 worker.1 | 2016-06-25T09:01:36.829Z 14784 TID-ouo1caxtw WARN: /Users/james/Source/theodi/octopub/app/models/dataset_file.rb:77:in `check_schema'
```

**Comment by Floppy** [comment]
@pezholio do S3 uploads and direct uploads get treated differently? One as string, one as file?

**Comment by Floppy** [comment]
Ah, it's coming in as a URL

**Comment by pezholio** [comment]
Yeah, you can probably reuse the `file_from_url` method from here https://github.com/theodi/octopub/blob/master/app/models/dataset_file.rb#L12 to turn it into a local file, probably somewhere in the `check_schema` callback (https://github.com/theodi/octopub/blob/master/app/models/dataset.rb#L228)

**Comment by Floppy** [comment]
Yak

**Comment by pezholio** [comment]
Took me a second to work out what that was :)

**Comment by Floppy** [comment]
Mmm, my tests do not reflect the reality of things coming from S3. Now my file is a URL I think, not a tempfile. Maybe that's good, but I'm not sure how to test it.

**Comment by pezholio** [comment]
This happened when we changed to s3 uploading with files too - there's a helper method here that you can use https://github.com/theodi/octopub/blob/master/spec/spec_helper.rb#L64

**Comment by Floppy** [comment]
Ta. I'm programming by coincidence here, so taking a break for a bit. Back later.

**Comment by pezholio** [comment]
I have progress. We're now assuming all schemas are a url string without a protocol, but this causes fail when updating, as there's a method that gets that schema from the datapackage and creates a fake uploaded file (https://github.com/theodi/octopub/blob/integrate-csv2rest/app/models/dataset.rb#L188). We need to think about how we handle this now - especially as, as it stands, CSV on the Web schemas are not persisted!

**Comment by pezholio** [comment]
Added some more commits and all the tests pass, but this now doesn't work in dev. It seems that if I add a schema, the `create_in_github` callback doens't get called. Man, fuck Rails.

**Comment by pezholio** [comment]
And, to further muddy the waters, this ONLY happens with CSV on the Web schemas

**Comment by pezholio** [comment]
I see now - at this point https://github.com/theodi/octopub/blob/integrate-csv2rest/app/models/dataset_file.rb#L100 `dataset` does not have a repo created, as `create_in_github` happens after creation

**Comment by pezholio** [comment]
This now works (with the caveat that the tests need a bit of rejigging) but with the fixtures I'm using (`valid-cotw.csv` and `csv-on-the-web-schema.json`), this line https://github.com/theodi/octopub/blob/integrate-csv2rest/app/models/dataset_file.rb#L90 throws this error (currently masked by a `rescue` that I nailed in):

```
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/stuart/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/csv2json-aea935b07ca4/lib/csvlint/csvw/csv2json/csv2json.rb:93:in `initialize_result'
``` 

This smells like a problem with csv2json

**Comment by Floppy** [comment]
Super helpful @pezholio thanks. It was all the callbacks and so on in here that I was getting really wound up in. I think this will want a heavy refactor soon.

**Comment by pezholio** [comment]
Yeah, totally. There's way too much going on with the callbacks etc. Might be more sensible to call the methods manually. Would make the tests waaaaay simpler too.

**Comment by Floppy** [comment]
OK, this is now ready for merge. We still need to:

* [ ] Make sure it handles multiple files correctly (especially ones that already exist)
* [ ] Generate human-readable views

But those can be done in separate PRs. @pezholio can you review?

**Comment by pezholio** [comment]
Looks good to me - the only possible breaking change is that we now expect the schema to come from S3, there's no non-JS fallback. Suggest we make a note of this, merge, then move on. Sound good?

**Comment by Floppy** [comment]
I guess so, yes. But that's already the case for files, I suppose?

**Comment by pezholio** [comment]
Nah, files works either way by creating a fake uploaded file (we need to support both methods for the API)

**Comment by Floppy** [comment]
OK, I think for alpha, let's note it and move on.

**Pull request merged**
